module.exports = [
  {
    id: 1,
    title: 'Sorry Albert Vishi',
    artist: 'Alan Walker',
    copyright: 'Studio records',
    purchase_price: 2,
    prolongation_price: 1.5,
    charge_period: 7,
    link: 'Alan_Walker_Sorry_Albert_Vishi_Remix.mp3',
    image: 'Alan_Walker_Sorry_Albert_Vishi_Remix.jpg',
  },
  {
    id: 2,
    title: 'Vesna',
    artist: 'Asnova Corporation',
    copyright: 'Studio records',
    purchase_price: 1,
    prolongation_price: 0.5,
    charge_period: 5,
    link: 'Asnova_Corporation_Vesna.mp3',
    image: 'Asnova_Corporation_Vesna.png',
  },
  {
    id: 3,
    title: 'Your Love 9 PM',
    artist: 'ATB Topic A7',
    copyright: 'Studio records',
    purchase_price: 3,
    prolongation_price: 2,
    charge_period: 10,
    link: 'ATB__Topic_A7S_Your_Love_9_PM.mp3',
    image: 'ATB__Topic_A7S_Your_Love_9_PM.jpg',
  },
  {
    id: 4,
    title: 'All My Life',
    artist: 'Attack&Attack',
    copyright: 'Studio records',
    purchase_price: 2,
    prolongation_price: 1,
    charge_period: 5,
    link: 'Attack_Attack_All_My_Life.mp3',
    image: 'Attack_Attack_All_My_Life.jpg',
  },
  {
    id: 5,
    title: 'Na Devyatke',
    artist: 'Dead Blonde Malchick',
    copyright: 'Studio records',
    purchase_price: 3,
    prolongation_price: 2,
    charge_period: 7,
    link: 'Dead_Blonde_MalÊ¹cik_Na_Devatke.mp3',
    image: 'Dead_Blonde_MalÊ¹cik_Na_Devatke.jpg',
  },
  {
    id: 6,
    title: 'The Night',
    artist: 'Disturbed',
    copyright: 'Studio records',
    purchase_price: 2,
    prolongation_price: 1,
    charge_period: 6,
    link: 'Disturbed_The_Night.mp3',
    image: 'Disturbed_The_Night.jpg',
  },
  {
    id: 7,
    title: 'Bird Machine',
    artist: 'Dj SnakeAlesia',
    copyright: 'Studio records',
    purchase_price: 2.5,
    prolongation_price: 2,
    charge_period: 7,
    link: 'Dj_SnakeAlesia_Bird_Machine.mp3',
    image: 'Dj_SnakeAlesia_Bird_Machine.jpg',
  },
  {
    id: 8,
    title: 'FOOL Criminals',
    artist: 'Monstercat',
    copyright: 'Studio records',
    purchase_price: 2,
    prolongation_price: 1,
    charge_period: 7,
    link: 'FOOL_Criminals_Monstercat_EP_Release.mp3',
    image: 'FOOL_Criminals_Monstercat_EP_Release.jpg',
  },
  {
    id: 9,
    title: 'Oh_La_La',
    artist: 'Gabry_Ponte feat Mougleta',
    copyright: 'Spinning records',
    purchase_price: 1,
    prolongation_price: 1,
    charge_period: 4,
    link: 'Gabry_Ponte_Oh_La_La_feat_Mougleta_Extended_Mix.mp3',
    image: 'Gabry_Ponte_Oh_La_La_feat_Mougleta_Extended_Mix.jpg',
  },
  {
    id: 30,
    title: 'Flashbacks',
    artist: 'Inna',
    copyright: 'Spinning records',
    purchase_price: 2.5,
    prolongation_price: 2,
    charge_period: 7,
    link: 'Inna_Flashbacks.mp3',
    image: 'Inna_Flashbacks.jpg',
  },
  {
    id: 10,
    title: 'Gardemariny vpered',
    artist: 'USSR',
    copyright: 'Stalin records',
    purchase_price: 5,
    prolongation_price: 5,
    charge_period: 10,
    link: 'Iz_filÊ¹ma_Gardemariny_vpered_Melodia_pesni_o_lubvi.mp3',
    image: 'Iz_filÊ¹ma_Gardemariny_vpered_Melodia_pesni_o_lubvi.jpg',
  },
  {
    id: 11,
    title: 'BED',
    artist: 'Joel Corry Raye feat David Guetta',
    copyright: 'Spinning records',
    purchase_price: 2,
    prolongation_price: 1,
    charge_period: 7,
    link: 'Joel_Corry_RAYE__David_Guetta_BED.mp3',
    image: 'Joel_Corry_RAYE__David_Guetta_BED.jpg',
  },
  {
    id: 12,
    title: 'Paparazzi',
    artist: 'Kim Dracula',
    copyright: 'Spinning records',
    purchase_price: 1,
    prolongation_price: 0.5,
    charge_period: 5,
    link: 'Kim_Dracula_Paparazzi.mp3',
    image: 'Kim_Dracula_Paparazzi.jpg',
  },
  {
    id: 13,
    title: 'Lit',
    artist: 'King Kevo',
    copyright: 'Spinning records',
    purchase_price: 3,
    prolongation_price: 2.5,
    charge_period: 10,
    link: 'King_Kevo_Lit.mp3',
    image: 'King_Kevo_Lit.jpg',
  },
  {
    id: 14,
    title: 'Call Me By Your Name',
    artist: 'Lil Nas X MONTERO',
    copyright: 'Spinning records',
    purchase_price: 2,
    prolongation_price: 1,
    charge_period: 7,
    link: 'Lil_Nas_X__MONTERO__Call_Me_By_Your_Name.mp3',
    image: 'Lil_Nas_X__MONTERO__Call_Me_By_Your_Name.jpg',
  },
  {
    id: 15,
    title: 'Calling My Phone',
    artist: 'Lil Tjay',
    copyright: 'Spinning records',
    purchase_price: 3,
    prolongation_price: 2,
    charge_period: 7,
    link: 'Lil_Tjay__6LACK_Calling_My_Phone.mp3',
    image: 'Lil_Tjay__6LACK_Calling_My_Phone.jpg',
  },
  {
    id: 16,
    title: 'ZITTI E BUONI',
    artist: 'Maneskin',
    copyright: 'Spinning records',
    purchase_price: 2,
    prolongation_price: 1.5,
    charge_period: 7,
    link: 'Maneskin_ZITTI_E_BUONI.mp3',
    image: 'Maneskin_ZITTI_E_BUONI.jpg',
  },
  {
    id: 17,
    title: 'Me Provocas',
    artist: 'Dynoro and Fumaratto',
    copyright: 'Spinning records',
    purchase_price: 1,
    prolongation_price: 0.5,
    charge_period: 5,
    link: 'Me_Provocas_Dynoro_and_Fumaratto.mp3',
    image: 'Me_Provocas_Dynoro_and_Fumaratto.jpg',
  },
  {
    id: 18,
    title: 'zmea',
    artist: 'MriD Adovitaa',
    copyright: 'Spinning records',
    purchase_price: 2,
    prolongation_price: 1.5,
    charge_period: 7,
    link: 'MriD_Adovitaa_zmea.mp3',
    image: 'MriD_Adovitaa_zmea.jpg',
  },
  {
    id: 19,
    title: 'Night and Day',
    artist: 'Odyssey',
    copyright: 'Spinning records',
    purchase_price: 2,
    prolongation_price: 1.5,
    charge_period: 7,
    link: 'Odyssey_Night_and_Day.mp3',
    image: 'Odyssey_Night_and_Day.jpg',
  },
  {
    id: 20,
    title: 'Inoplanetane',
    artist: 'Prosto Lera',
    copyright: 'Spinning records',
    purchase_price: 3,
    prolongation_price: 2,
    charge_period: 10,
    link: 'Prosto_Lera_Inoplanetane.mp3',
    image: 'Prosto_Lera_Inoplanetane.jpg',
  },
  {
    id: 21,
    title: 'Tattoo',
    artist: 'Rammstein',
    copyright: 'Spinning records',
    purchase_price: 2,
    prolongation_price: 1.5,
    charge_period: 7,
    link: 'Rammstein_Tattoo.mp3',
    image: 'Rammstein_Tattoo.jpg',
  },
  {
    id: 22,
    title: 'Before I Die',
    artist: 'Scott Rill feat Dayana',
    copyright: 'Spinning records',
    purchase_price: 3,
    prolongation_price: 2,
    charge_period: 7,
    link: 'Scott_Rill__Dayana_Before_I_Die.mp3',
    image: 'Scott_Rill__Dayana_Before_I_Die.jpg',
  },
  {
    id: 23,
    title: 'Touche',
    artist: 'SICKOTOY',
    copyright: 'Spinning records',
    purchase_price: 2,
    prolongation_price: 1.5,
    charge_period: 7,
    link: 'SICKOTOY__Touche.mp3',
    image: 'SICKOTOY__Touche.jpg',
  },
  {
    id: 24,
    title: 'Nothing Burns Like the Cold',
    artist: 'Snoh Aalegra',
    copyright: 'Spinning records',
    purchase_price: 2,
    prolongation_price: 1.5,
    charge_period: 7,
    link: 'Snoh_Aalegra_Nothing_Burns_Like_the_Cold.mp3',
    image: 'Snoh_Aalegra_Nothing_Burns_Like_the_Cold.jpg',
  },
  {
    id: 25,
    title: 'Prosto tak',
    artist: 'StaFFord63',
    copyright: 'Spinning records',
    purchase_price: 3,
    prolongation_price: 2.5,
    charge_period: 10,
    link: 'StaFFord63_Prosto_tak.mp3',
    image: 'StaFFord63_Prosto_tak.jpg',
  },
  {
    id: 26,
    title: 'Brooklyn Blood Pop',
    artist: 'Syko',
    copyright: 'Spinning records',
    purchase_price: 1,
    prolongation_price: 0.5,
    charge_period: 5,
    link: 'Syko_BrooklynBloodPopâ.mp3',
    image: 'Syko_BrooklynBloodPopâ.jpg',
  },
  {
    id: 27,
    title: 'Baby',
    artist: 'Tesher Jalebi',
    copyright: 'Spinning records',
    purchase_price: 2,
    prolongation_price: 1.5,
    charge_period: 7,
    link: 'Tesher_Jalebi_Baby.mp3',
    image: 'Tesher_Jalebi_Baby.jpg',
  },
  {
    id: 28,
    title: 'Save Your Tears',
    artist: 'The Weeknd feat Ariana Grande',
    copyright: 'Spinning records',
    purchase_price: 4,
    prolongation_price: 3,
    charge_period: 14,
    link: 'The_Weeknd__Ariana_Grande_Save_Your_Tears_Remix.mp3',
    image: 'The_Weeknd__Ariana_Grande_Save_Your_Tears_Remix.jpg',
  },
  {
    id: 29,
    title: 'AjAjAj',
    artist: 'Vavan Ruki Vverh',
    copyright: 'Spinning records',
    purchase_price: 2,
    prolongation_price: 1.5,
    charge_period: 7,
    link: 'Vavan__Ruki_Vverh_AjAjAj.mp3',
    image: 'Vavan__Ruki_Vverh_AjAjAj.jpg',
  },
];
